services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Digicademy\CHFMedia\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Digicademy\CHFMedia\EventListener\ExiftoolFileMetadataExtraction:
    tags:
      - name: event.listener
        identifier: 'chfExiftoolFileMetadataExtraction'